
title:  |
        | **Deaths and Disappearances in the Pinochet Regime: A New Dataset**
author: 
  - "Danilo Freire[^df]"
  - "John Meadowcroft[^jm]"
  - "David Skarbek[^ds]"
  - "Eugenia Guerrero[^eg]"
date: \today
thanks: "We thank Umberto Mignozzetti and Robert Myles McDonnell for their helpful comments. Data and replication information are available at [`http://github.com/danilofreire/pinochet`](http://github.com/danilofreire/pinochet)."
abstract: "... However, . This paper presents a georeferenced event dataset on "
keywords: "authoritarian regimes, Chile, georeferenced event data, Pinochet, truth commission"
fontfamily: libertine
fontawesome: yes
fontsize: 12pt
monospace-url: yes
spacing: double
papersize: a4paper
bibliography: references.bib
biblio-style: apalike
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    number_sections: yes
    keep_tex: no
    template: template.latex
---

# Introduction\label{sec:intro}

\setlength{\parindent}{1cm}
\setlength{\parskip}{0pt}

On 11 September 1973, Army General Augusto Pinochet led a coup against Chile's socialist President Salvador Allende. The coup marked the beginning of a seventeen-year military dictatorship that undertook a rapid liberalisation of the Chilean economy while perpetrating systematic violence against the opposition [@meadowcroft2014hayek; @valdes1995pinochet]. The extent of the human rights abuses during the Pinochet regime remains unknown. However, in 1991 then-President Patricio Aylwin created a commission to investigate the most serious violations that happened during the military period. The Report of the Chilean National Commission on Truth and Reconciliation [-@report1991], or the Rettig Report[^rettig], records over 2,000 cases of murders and disappearances. In most cases, there is some detail as to the personal characteristics of the victim, and where and when they died or disappeared, and in many cases there is information as to how that person died. The Report proved a major milestone in the pursuit of justice for the victims of the regime.

Although the Report is a valuable resource for scholars across the humanities, quantitative researchers cannot easily use the rich information it contains. In this paper, we present a manually-coded dataset with all information from the Truth Commission Report plus new variables we constructed to complement the original data. We transcribed every personal detail from the 903 pages of the English translation of the Report, assigned a unique identification number to each of the victims, then matched the location of the human rights abuses to geographic coordinates. We matched all cases which had spatial information available.

Apart from the geographical location of the incidents, our dataset also includes: 1) the sociological characteristics of the victim; 2) their affiliation (where known); 3) the type of violence that took place during that particular event; 4) whether the victim was interrogated, tortured or in some other way mistreated (if known); 5) who were the perpetrators of the violence. If the Report does not have a particular information, we coded it as missing. As each individual receives their own id number, new information can be added to the dataset as archival work on the Pinochet era progresses. In the following sections, we describe the dataset, show summary statistics for selected variables, then provide suggestions about how our data can answer future research questions.

# Historical Background



# The Dataset

Our dataset comprises 2,398 observations and 57 variables. As we noted above, each observation corresponds to a victim of the Pinochet regime and every individual has a unique id number. There are several variables describing personal information of the victims, such as age, gender, nationality, occupation, and political affiliation if available. The dataset also includes information about torture or assassination methods and geographical coordinates for a number of the incidents. Figure 01 shows an example entry from our dataset.

[comment]: <> (Example Entry)

Users can download the data as an Excel spreadsheet (`.xlsx`) or as a comma-separated values (`.csv`) file. We have also created an `R` package called `pinochet` which includes the dataset in both formats plus the codebook. The files follow the principles of "tidy data", where each column represents one variable and each row is one case [@wickham2014tidy]. The `pinochet` package is available for download on the Comprehensive R Archive Network (CRAN) and at <http://github.com/danilofreire/pinochet>. To make the data accessible, our GitHub repository has detailed installation instructions for users new to `R`.  

## Types of Violence

The Report distinguishes between different types of violence carried out by the Pinochet regime. The first type is _deaths_. These are cases where the Commission signals a definite and known death of the victim. Take the case of Benito Heriberto Torres Torres, one of the first victims of the Pinochet regime (id number 2). Our dataset shows that Mr Torres was male, 57 years-old, and that he worked as a plumber. On the 12 September 1973, just one day after the military coup, Mr Torres was torture on the way to the 26th police station in Santiago. The records indicate he executed and his body was later found in Las Barrancas, Santiago. The dataset also shows that we obtained this information from pages 159-160 of the Truth Commission Report. 

The second type of violence recorded in the dataset is _disappearances_. These are cases where government agents are presumed to have killed and disposed of the body of the victims. One such example is that of the Brazilian engineer Tulio Roberto Quintiliano Cardozo (id number 5). Mr Cardozo was a member of the Communist party and troops took him to the Military Academy for interrogation also on the 12 September 1971. He was never seen again and is presumed dead.  

The third category is _disappearance, information of death_. As the name implies, these observations refer to cases the Commission confirms the individual died after being missing. The formal definition for this category is that "the victims are dead; that they died at the hands of the government agents, or persons in their service; and that these or other agents disposed of the victims' mortal remains by throwing them into a river or a sea, by covertly burying them, or by disposing of them in some other secret fashion" [@report1991 44]. The assassination of Humberto de las Nieves Fuentes Rodriguez is an example (id number 854). He was taken in custody to the Colina air base, then loaded onto a helicopter with other political prisoners. According to the Report, government agents drugged him, beat him with a metal bar, opened his stomach with a knife before throwing the former Communist alderman from a helicopter. While his body has not been found, there is enough information about the case to classify his death as a severe human rights violation.  

The last group is that of _unresolved_ cases. These are defined as those where insufficient information or evidence is available. Our dataset counts 93 unresolved cases, many with georeferenced information about possible torture sites[^ambiguous]. However, it is very likely that the people who disappeared were, in fact, killed. Based on the report and our methodology, we can only determine that 65% of all of the cases led to an assassination. Forty percent of the documented cases are disappearances.  

[comment]: <> (Table 1 around here)

Although the Report provides a comprehensive list of the regime victims, the Chilean Truth Commission itself acknowledges that the data are incomplete. The Commission had only nine months to write the Report and it had no legal power to oblige citizens to cooperate. Therefore, we expect that some cases have not been recorded. But this problem is not unique to the Pinochet regime. Selection bias is a common feature in events data, even more so in datasets about armed conflict or government repression [@ball2019using; @chapman2001truth]. As the cases might not be a representative sample of the population of victims, we suggest scholars to carefully consider issues of model specification.

## Geocoding

We have georeferenced all observations for which the relevant data was available. Based on data from the Truth Commission, we first created a variable indicating where the victim was allegedly tortured or murder. We assigned a number to the six locations that most frequently appear in the report, namely: 1) home; 2) work; 3) university; 4) in custody; 5) in public; and 6) in hospital. We assigned "unknown" if the location could not be identified. Then we added latitude and longitude coordinates to each location where the individuals were seen. 

Since the Truth Commission Report includes spatial data in string format -- e.g., intersection of _Calle Grecia_ with _Avenida Rosa_ -- we mapped the locations using decimal degrees to increase precision. The mapping process is straightforward. We used three different websites to increase the coverage of our maps and include the largest possible number of observations. The first website we employed is Google Maps (<http://maps.google.co.uk>), the world's most widely used map software. We queried Google Maps' application programming interface (API) to search for street intersections and other precise addressed we retrieved from the Truth Commission Report. Additionally, we used the API to locate police stations and government buildings still in use.  

Next, we used Wikimapia (<https://wikimapia.org/>), a open-content collaborative platform that allows users to mark locations worldwide. As of March 2019, Wikimapia contains about 30 million places in its database[^wikimapia]. We benefited from this crowdsourced information to identify shanty-towns, military bases, and small neighbourhoods that could be easily found in general-purpose maps.  

Our third source of geographic coordinates is Latitude (<http://latitude.to>). We used Latitude to source inexact coordinates, such as coordinates for cities and towns. If no precise information was available, our measure of latitude and longitude correspond to those of the control point of each city. We also used the Latitude.to website to convert non-decimal coordinates to decimal ones. For instance, some addresses in Wikimapia are in degrees, minutes, and seconds (DMS) format, and to keep the dataset comparable all coordinates follow the same standard. 

## Variables and Patterns

As mentioned previously, our dataset includes 57 variables and covers the seventeen years of the Pinochet Presidency (1973--1990). Figure \ref{trend} shows the frequency of government-perpetrated incidents per month from 1973 to 1990. The data show us that the vast majority of the acts of violence happened in the first two months after the military coup. The high incidence of human rights violations in the beginning of the Pinochet era reflects the activity of the "Caravan of Death", a group of paramilitaries established in October 1973 to torture and kill dissidents [@davis1990they, 459; @verdugo2001chile]. 

[comment]: <> (Figure 02 - Time Trends Here)

In September 1973 alone, the government committed 633 acts of violence against civilians, of which 406 the Commission signals a definite and known death. The scale continued in October, with 504 incidences and 317 certified deaths. The numbers decline to about 10% of those levels in the next months, and then recede further in 1974.

In absolute numbers, the Chilean dictatorship was not as violent as its Argentinian counterpart,[^argentina] but the figures are notably high when compared to other South American countries. The Brazilian military regime made 434 victims from 1964 to 1985; Paraguay had 424 victims of human rights abuse from 1954 to 1989; Bolivia had 350 from 1964 to 1982; and Uruguay reported about 300 incidences from 1973 to 1985 [@agenciabrasil2014ditadura; @elpais2014ditadura; @fsp2016argentina]. The distribution of events over time seem to differ as well. Despite eventual periods of higher intensity, violence in authoritarian Brazil stretched somewhat evenly during the regime [@agenciabrasil2014ditadura; @elpais2014ditadura]. The Stroessner regime in Paraguay also constantly employed violence against the opposition [@cvj2008paraguay].




# Conclusion: New Avenues for Research

In this paper, we introduce a dataset with rich information about more than 2,000 victims of the Pinochet regime. Our data come from two sources. First, we manually coded all information available in the Report of the Chilean National Commission on Truth and Reconciliation [-@report1991]. Second, we added the geographical locations and the specific dates of the human rights abuses whenever we could retrieve them. The graphs and maps included in this article provide some preliminary results about the temporal and spatial variation of state violence during Chile's last military government.

We believe our data open new topics of research. For instance, @lupu2017legacy, @rozenas2017political and @zhukov2018stalin highlight that state repression has enduring effects on political preferences and social attitudes. Researchers can test whether the Pinochet regime has caused similar attitudinal changes in direct or indirect victims. Moreover, sociologists and criminologists can analyse the relationship between human rights abuses and post-regime levels of interpersonal violence. Recent studies show that democracies which arise after military regimes have higher homicide rates [@frantz2018legacy; @karstedt2006democracy]. Our data can show if areas with significant levels of military repression are more violent today.	

Researchers can also examine how political coalitions affect the use of lethal violence in authoritarian regimes. Although the topic has received increasing attention [e.g., @fjelde2010generals; @gandhi2007authoritarian; @rivera2017authoritarian], the internal dynamics of autocratic governments remains understudied. The main reason is a lack of fine-grained information [@ferrara2014assessing, 16]. By linking human right abuses to changes in Pinochet's coalition, scholars can explore whether civilian or bureaucratic support lead to higher incidence of state violence. The individual data presented here can be combined with government records at any level of aggregation. 

Qualitative scholars will find the personal details of the victims to be particularly useful. Historians willing to reconstruct the biographies of specific individuals are able to access pre-compiled information in a single digital file. Others might be interested in using our data as a starting point for network analysis or to collect oral testimony from survivors and acquaintances. In that regard, the dataset can accommodate future qualitative information. As we include a unique identification number to each victim, it is easy to update the personal record of any individual with new data from public archives or personal correspondence. 

Lastly, scholars can investigate the connections between international legitimacy and domestic politics in repressive regimes. This is a promising area of research as the Chilean government and American intelligence services continue to declassify documents from the Pinochet era. One relevant question is whether pressure from foreign governments and organisations had any influence over the levels of human rights abuses in Chile. We hope our dataset is useful for scholars interested in these and other questions, and that the information it contains elicits hypotheses not only about the Pinochet period, but about authoritarian governments more generally.

[^df]: Postdoctoral Research Fellow, The Political Theory Project, Brown University, 8 Fones Alley, Providence, RI 02912, [`danilofreire@gmail.com`](mailto:danilofreire@gmail.com), [`http://danilofreire.github.io`](http://danilofreire.github.io). Corresponding author.

[^jm]: Senior Lecturer in Public Policy, Department of Political Economy, King's College London, [`john.meadowcroft@kcl.ac.uk`](mailto:john.meadowcroft@kcl.ac.uk), [`http://johnmeadowcroft.net`](http://johnmeadowcroft.net).

[^ds]: Associate Professor, Department of Political Science and the Political Theory Project, Brown University, [`david_skarbek@brown.edu`](david_skarbek@brown.edu), [`http://davidskarbek.com`](http://davidskarbek.com).

[^eg]: Software Developer, Tempo UK.

[^rettig]: Former Chilean ambassador Raúl Rettig chaired the Chilean National Commission for Truth and Reconciliation. 

[^ambiguous]: Two cases are ambiguously described in the Truth and Commission Report, so we treat them as missing data. The victims are Ruiter Enrique Correa Arce, a news stand owner accused of facilitating message exchanges between party leaders (id number 843), and Alonso Fernando Gahona Chavez, a communist leader of municipal workers of La Cisterna (id number 847).

[^wikimapia]: Wikimapia statistics for March 2019 are available at <https://wikimapia.org/stats/action_stats/?fstat=2&period=3&year=2019&month=3>.

[^argentina]: The Argentinian government disputes the figure of 30,000 deaths and disappearances human rights organisations often suggest [@bbc2016argentina; @elpais2016argentina]. Ceferino Reato, a writer and journalist, indicates that there were 7,158 incidences during the regime, including 6,415 cases of disappearances and 743 victims of summary executions [@clarin2016argentina]. However, General Jorge Rafael Videla, who ruled Argentina from 1976 to 1981, seems to agree with those figures. He once remarked that killing "about 7 or 8 thousand people" was "the price of winning the war against the subversives" [@clarin2012videla].


\newpage
\setlength{\parindent}{0cm}
\setlength{\parskip}{6pt}
